### ISSUE TITLE
[FEAT] 작업 된 뷰의 Navigation 진행

### ISSUE THREAD

**Issue by empty005** [3chuu/Poketochip#29]
**Description**
뷰 연결 작업 진행

**Todo**
- [ ] 프로토 타입 느낌으로다가 
- [ ] 탭바 - 각 상세페이지 연결 = 차녕
- [ ] 버튼 ~ 17일까지 미비사항) 재 점검

**Etc**
기타 사항
